server:
  port: 8000

spring:
  application:
    name: api-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${API_DB_URL}
    username: ${API_DB_USER}
    password: ${API_DB_PASSWORD}

  jpa:
    defer-datasource-initialization: false
    generate-ddl: false

    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc:
          time_zone: UTC

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_INTERNAL:http://auth-server:9000/auth}
          jwk-set-uri: ${AUTH_SERVER_INTERNAL:http://auth-server:9000/auth}/oauth2/jwks

  data:
    redis:
      host: ${API_REDIS_HOST}
      port: ${API_REDIS_PORT}
      password: ${API_REDIS_PASSWORD}
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}
    register-with-eureka: true
    fetch-registry: true

app:
  sqids:
    min-length: 10
  redis:
    namespaces:
      stock: inv:stock
      referral-codes: referral:codes
  meilisearch:
    host: ${MEILISEARCH_HOST:http://localhost:7700}
    api-key: ${MEILISEARCH_MASTER_KEY:masterkey}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG